### ISSUE TITLE
Add slack E-mail as metadata when posting events to map userid + email

### ISSUE THREAD

**Issue by kamigerami** [codelabsab/timereport-slack#72] opened 2019-02-24 02:53 UTC
We need to be able to map a slack userid and username to an actual E-mail address.

To solve this we need to add metadata to dynamodb as a separate table or a new field.

This ticket is about querying for E-mail data using slack.

**How to solve:** 
Leverage: 
https://api.slack.com/scopes/users:read.email

and add this metadata to dynamodb. 

**This data will be used in the future by:**
- UI (for whenever user logs in only display his own users entries)
- Notifying users via E-mail if a month is not locked
- Creating invoices and salaries which needs an actual E-mail address tied to a user.
- Maybe we could leverage G-suite to get proper names of that user in the future as well

**Comment by parberge** [comment] 2019-02-24 08:15
So we have to add this to what we insert into DB?

**Comment by parberge** [comment] 2019-02-25 08:21
Is this a duplicate of #66 ?

**Comment by kamigerami** [comment] 2019-02-26 09:20
No not a duplicate - #66  was already implemented in the backend

**Comment by kamigerami** [comment] 2019-02-26 09:21
I think this can be a lower priority since for now and will be good if we implement login functionality to the frontend UI and CRUD directly from the frontend then we might want to have these mapped (as well as invoice functionality)

**Comment by parberge** [comment] 2019-03-11 18:36
I don't really understand what this ticket means.

Can you try to explain a bit more @kamigerami ? Maybe as small psudo code to show what you mean?

**Comment by parberge** [comment] 2019-09-27 19:28
@kamigerami Is this still valid?

**Comment by kamigerami** [comment] 2019-10-09 18:00
can we somehow get from the SLACK api the user-mail address ? and maybe extract the name from that?

**Comment by parberge** [comment] 2019-10-09 20:13
I still don't understand why we need this ☺️

**Comment by kamigerami** [comment] 2019-10-18 16:48
Ok. So let's imagine time report is being used for generating invoices and salaries ... how can we map our ugly slack names kamger, par.berge etc .. to real usernames and E-mails? How would a third party system know which user kamger or par.berge is? they would need to know our actual name or our actual E-mail address or something to identify us.... this ticket is about adding this information to the database as meta-data somehow ..  so let's say a new user creates his first entry .. then it should add a metadata about the user somehow preferably by means of the information that is registered in the client (slack in this case). next entry .. even if the table or metadata already exists it should not matter if it tries to add it again or not .. it should be idempotent.. thoughts?

**Comment by parberge** [comment] 2019-10-18 16:56
I guess email would be good enough identifier. So this ticket is more about adding more data into the database for each "event". Maybe you can clarify the ticket title and description

**Comment by parberge** [comment] 2019-10-21 08:15
We talked about this on slack. @kamigerami can you please update the ticket with what we decided?

**Comment by kamigerami** [comment] 2019-10-21 15:28
how about now?

**Comment by parberge** [comment] 2019-10-21 18:24
I used https://api.slack.com/methods/conversations.list when I did a PoC of this on slack. I don't know what's better. It's up to the implementer to decide I guess

**Comment by parberge** [comment] 2019-11-13 10:52
During discussion we decided to implement this into a separate table and this table should be controlled by other means than timereport-slack

**Closed by parberge** 2019-11-13 10:52 UTC
Labels: enhancement
