### ISSUE TITLE
DeprecationWarning - Change package for post() function from botocore to requests

### ISSUE THREAD

**Issue by kamigerami** [codelabsab/timereport-slack#121] opened 2019-10-19 01:54 UTC
In the cloudwatch logs for timereport-slack:

```
/var/runtime/botocore/vendored/requests/api.py:67: DeprecationWarning: You are using the post() function from 'botocore.vendored.requests'. This is not a public API in botocore and will be removed in the future. Additionally, this version of requests is out of date. We recommend you install the requests package, 'import requests' directly, and use the requests.post() function instead.
DeprecationWarning
```

**Comment by parberge** [comment] 2019-10-19 07:00
Duplicate of #82

**Closed by parberge** 2019-10-19 07:00 UTC
Labels: bug, needs_verification
